version: '3.6'
services:
  # Main API (Required)
  service:
    container_name: sonolus_fastapi_service
    hostname: sonolus_fastapi_service
    build:
      context: .
    volumes:
      - ${VOLUME_API_PATH}:/var/lib/mysql:delegated
    ports:
      - ${PORT_API}:8080
    networks:
      - local-net
    depends_on:
      - database
  # SUS convertion server (Required)
  # Run at sonolus_sus_service:3000
  sus:
    image: dosugamea/sonolus-sus-server:latest
    container_name: sonolus_sus_service
    hostname: sonolus_sus_service
    networks:
      - local-net
    depends_on:
      - service
    ports:
      - ${PORT_SUS}:3000
    environment:
      S3_KEY: ${S3_KEY}
      S3_SECRET: ${S3_SECRET}
      S3_BUCKET: ${S3_BUCKET}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
  # MariaDB Database (Required)
  database:
    container_name: sonolus_fastapi_database
    hostname: sonolus_fastapi_database
    image: mariadb
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ${VOLUME_DB_PATH}:/var/lib/mysql:delegated
    ports:
      - ${PORT_DB}:3306
    networks:
      - local-net
    environment:
      - MYSQL_ROOT_Host='%'
      - MYSQL_ROOT_PASSWORD=${DB_ROOT}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - TZ='Asia/Tokyo'
  # Database web console (Optional)
  adminer:
    image: adminer:latest
    container_name: sonolus_fastapi_adminer
    hostname: sonolus_fastapi_adminer
    restart: always
    ports:
      - ${PORT_ADMINER}:8080
    networks:
      - local-net
    depends_on:
      - database
  # Local S3 with web console (Optional)
  minio:
    image: minio/minio
    volumes:
      - ${VOLUME_MINIO_PATH}:/${S3_BUCKET}
    ports:
      - ${PORT_MINIO}:9000
      - ${PORT_MINIO_CONSOLE}:9001
    environment:
      MINIO_ACCESS_KEY: ${S3_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET}
    command: ["server", "--console-address", ":9001", "${S3_BUCKET}"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - local-net
  # Local S3 initialization script (Optional)
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 ${S3_KEY} ${S3_SECRET}) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/${S3_BUCKET};
      /usr/bin/mc policy download myminio/${S3_BUCKET};
      exit 0;
      "
    networks:
      - local-net
  # Firebase auth emulator for development (Optional)
  firebase:
    image: andreysenov/firebase-tools:latest
    command: firebase emulators:start
    volumes:
      - ./:/home/node
    ports:
      - ${PORT_FIREBASE_EMULATOR}:4000
      - 9099:9099
    networks:
      - local-net
networks:
  local-net:
    driver: bridge