name: Run test
on: [push]
jobs:
  test:
    name: CI
    timeout-minutes: 5
    runs-on: ubuntu-latest
    environment:
      name: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Create .env file
        run: mv .env_test .env
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Load cached dependencies
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      - name: docker-compose up
        run: docker-compose up -d
      - name: Run Test
        run: |
          poetry run pytest --cov --cov-report=xml
      - name: Upload result to codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage.xml
          name: codecov-umbrella # optional
          flags: unittests # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)